#!/usr/bin/env python3
"""
French for the 781 evidence / clue / task labels shown on the mindmap, in the
journal and in the evidence lists. Keyed by the English DISPLAY string
(altLabel when set, else label — see InvItem.GetTranslatableString(0)).

Conventions (docs/STYLE.md):
  - sentence case, not English title case
  - Mister/Miss/Missus -> M./Mlle/Mme ; Father -> le père ; Doctor -> le docteur
  - Master Blake -> le jeune maître Blake ; Marquess/Marchioness -> le marquis / la marquise
  - Irish and Italian in-world terms are left untouched (magic words, place names, deities)
  - task verbs are fixed: Investigate->Enquêter sur, Search->Fouiller,
    Research->Se documenter sur, Find->Trouver, Ask About->S'enquérir de, Profile->Profiler

Disambiguated against the dialogue corpus, not guessed:
  Staff = the hotel personnel (94 dialogue hits, no magical staff anywhere)
  Discs = voltaic-pile discs   Vats = cuves   Fetters = what binds a ghost
  Crown = the British Crown    Slides = magic-lantern slides

StreamingAssets/MindmapCSVs/*.txt are NOT a text source: no assembly reads them,
and their contents are stale design scratch (they still say "Ivy Darroch", a name
the shipped game replaced with "Ivy McLeod").
"""

EVIDENCE = {
    # ---------------------------------------------------------------- people
    "Arwa Hisham": "Arwa Hisham",
    "Caitlin Joyce": "Caitlin Joyce",
    "Carmela Mantovani": "Carmela Mantovani",
    "Cathal O'Meara": "Cathal O’Meara",
    "Corentine Quinn": "Corentine Quinn",
    "Darragh Hunter": "Darragh Hunter",
    "Domhnall Ó Finn": "Domhnall Ó Finn",
    "Etienne Toussaint": "Etienne Toussaint",
    "Evelyn Deane": "Evelyn Deane",
    "Father Lorcan Sinnott": "Le père Lorcan Sinnott",
    "Father Sinnott": "Le père Sinnott",
    "Fiadh Callaghan": "Fiadh Callaghan",
    "Hazel Erickson": "Hazel Erickson",
    "Henry Blake": "Henry Blake",
    "Ines Barbosa": "Ines Barbosa",
    "Ivy McLeod": "Ivy McLeod",
    "Jonathan Blake": "Jonathan Blake",
    "Lady Wilhelmina Blake": "Lady Wilhelmina Blake",
    "Lloyd Dupré": "Lloyd Dupré",
    "Marquess Blake": "Le marquis Blake",
    "Mary Blake": "Mary Blake",
    "Master Blake": "Le jeune maître Blake",
    "Michael Skerritt": "Michael Skerritt",
    "Miss Barbosa": "Mlle Barbosa",
    "Miss Callaghan": "Mlle Callaghan",
    "Miss Deane": "Mlle Deane",
    "Miss Joyce": "Mlle Joyce",
    "Miss Mantovani": "Mlle Mantovani",
    "Miss McLeod": "Mlle McLeod",
    "Miss Murphy": "Mlle Murphy",
    "Miss Quinn": "Mlle Quinn",
    "Missus D'Arcy": "Mme D’Arcy",
    "Missus Lau": "Mme Lau",
    "Mister Coventry": "M. Coventry",
    "Mister Doyle": "M. Doyle",
    "Mister Dupré": "M. Dupré",
    "Mister Hunter": "M. Hunter",
    "Mister O'Meara": "M. O’Meara",
    "Mister Skerritt": "M. Skerritt",
    "Mister Toussaint": "M. Toussaint",
    "Mister Varley": "M. Varley",
    "Mister Ó Finn": "M. Ó Finn",
    "Olivia D'Arcy": "Olivia D’Arcy",
    "Ruairi Callaghan": "Ruairi Callaghan",
    "Saoirse Murphy": "Saoirse Murphy",
    "Seamus Doyle": "Seamus Doyle",
    "Seamus O'Connor": "Seamus O’Connor",
    "Simon Coventry": "Simon Coventry",
    "Victoria Lau": "Victoria Lau",
    "Vincent Varley": "Vincent Varley",
    "Walter Blake": "Walter Blake",
    "Doctor Callaghan": "Le docteur Callaghan",
    "The Recluse": "Le reclus",
    "Washer Woman": "La blanchisseuse",
    "Jeweller": "Le joaillier",
    "Druid": "Druide",
    "Chaperone": "Chaperon",
    "Mistress": "Maîtresse",
    "Protector": "Protecteur",
    "Martyr": "Martyr",
    "Apprentice: Ruairí Callaghan": "Apprenti : Ruairí Callaghan",
    "Mentor: Fiadh Callaghan": "Mentor : Fiadh Callaghan",
    "Target: Hazel Erickson": "Cible : Hazel Erickson",

    # ------------------------------------------------------- myth & religion
    "Abhartach": "Abhartach",
    "Aisfhill": "Aisfhill",
    "Ataispeáin": "Ataispeáin",
    "Bean Draoí": "Bean Draoí",
    "Bean Draoí Duties": "Devoirs de la Bean Draoí",
    "Brat Bhride": "Brat Bhríde",
    "Cuimhnigh\n": "Cuimhnigh\n",
    "Díghlasáil": "Díghlasáil",
    "Dúisigh": "Dúisigh",
    "Dún": "Dún",
    "Macallaigh": "Macallaigh",
    "Ogham": "Ogham",
    "Oscail": "Oscail",
    "Poitín": "Poitín",
    "Scaoil": "Scaoil",
    "Scrois": "Scrois",
    "Suibne": "Suibne",
    "Tuatha Dé Danann": "Tuatha Dé Danann",
    "Tír Na NÓg": "Tír Na NÓg",
    "Milesians": "Milésiens",
    "Three Milesian Rulers": "Les trois souverains milésiens",
    "Notes On Milesian Bloodlines": "Notes sur les lignées milésiennes",
    "The God, Goibniu": "Le dieu Goibniu",
    "The Goddess, An Cailleach": "La déesse An Cailleach",
    "The Goddess, An Morrigan": "La déesse An Morrigan",
    "The Goddess, Bríd": "La déesse Bríd",
    "Maman Brigitte": "Maman Brigitte",
    "Fae": "Fae",
    "The Fae": "Les Fae",
    "Angels": "Anges",
    "Angel Sketches": "Croquis d’anges",
    "Enochian Magic": "Magie énochienne",
    "Freemasons": "Francs-maçons",
    "Freemason Correspondence": "Correspondance maçonnique",
    "H.O.G.D.": "H.O.G.D.",
    "Hermetic Order Of The Golden Dawn": "Ordre hermétique de l’Aube dorée",
    "Society Of Psychical Research Symbol": "Symbole de la Society for Psychical Research",
    "The Aeon": "L’Éon",
    "The Black Iron Prison": "La prison de fer noir",
    "Leviticus 20:27": "Lévitique 20, 27",
    "Cross Of Saint Brigid": "Croix de sainte Brigide",
    "Saint Brigid's Cross": "Croix de sainte Brigide",
    "Celtic Cross Necklace": "Collier à croix celtique",
    "Celtic Cross Tie Pin": "Épingle de cravate à croix celtique",
    "Unusual Celtic Cross": "Croix celtique singulière",
    "Unusual Cross": "Croix singulière",
    "Stone Cross": "Croix de pierre",
    "Exorcism": "Exorcisme",
    "Sacrifice": "Sacrifice",
    "False Sacrifice": "Faux sacrifice",
    "Atone": "Expier",
    "Memento Mori": "Memento mori",
    "Curse": "Malédiction",
    "Lift The Curse": "Lever la malédiction",
    "Magic": "Magie",
    "Learning Magic": "Apprendre la magie",
    "Magical Phrase": "Formule magique",
    "Magic Doorway": "Porte magique",
    "Wards Of Protection": "Sceaux de protection",
    "Soul Jars": "Jarres d’âmes",
    "Summoning Ritual": "Rituel d’invocation",
    "Summon The Three Aspects": "Invoquer les trois aspects",
    "Third Aspect": "Troisième aspect",
    "Second Sight": "Double vue",
    "Séance": "Séance",
    "The Grand Séance": "La Grande Séance",
    "Séance Aftermath": "Les suites de la Séance",
    "Séance Contract": "Contrat de la Séance",
    "Séance Disaster": "Le désastre de la Séance",
    "Séance Ghost": "Fantôme de la Séance",
    "Séance Survivors": "Survivants de la Séance",
    "Séance Victims": "Victimes de la Séance",
    "Conductor Of The Séance": "Officiant de la Séance",
    "Motivation For The Séance": "Mobile de la Séance",
    "Stop The Séance": "Arrêter la Séance",
    "Vandalised Séance Flyer": "Prospectus de la Séance vandalisé",

    # ------------------------------------------------------- the supernatural
    "The Entity": "L’Entité",
    "Shadowy Figure": "Silhouette dans l’ombre",
    "Mysterious Figure In Window": "Silhouette mystérieuse à la fenêtre",
    "Ghost At Firepit": "Fantôme du foyer",
    "Ghostly Message": "Message spectral",
    "Father's Ghost": "Le fantôme du père",
    "Hauntings": "Hantises",
    "Haunted Expression": "Expression hantée",
    "Fetters": "Entraves",
    "Rift": "Faille",
    "Portal": "Portail",
    "A Portal": "Un portail",
    "Is There A Portal Here?": "Y a-t-il un portail ici ?",
    "Place Of Power": "Lieu de pouvoir",
    "Vision": "Vision",
    "Hedge Maze Vision": "Vision du labyrinthe",
    "Altered Reality": "Réalité altérée",
    "Buried Messages": "Messages enfouis",
    "Strange Occurrences": "Phénomènes étranges",
    "Strange Light": "Lueur étrange",
    "Near-Death Experience": "Expérience de mort imminente",
    "Doomed To Die": "Condamné à mourir",
    "Ready To Face Death": "Prêt à affronter la mort",
    "Put Ghost To Rest": "Apaiser le fantôme",
    "Commune With Firepit Ghost": "Communier avec le fantôme du foyer",
    "Walled-up Lovers": "Amants emmurés",
    "Hammering Giant": "Le géant au marteau",
    "Crows": "Corbeaux",
    "Aunt's Shadow": "L’ombre de la tante",

    # --------------------------------------------------------------- dreams
    "Dream Lucidly": "Rêver en pleine conscience",
    "Dream Symbol": "Symbole onirique",
    "Lucid Dreaming": "Rêve lucide",
    "Shared Dreams": "Rêves partagés",
    "Shared Thoughts": "Pensées partagées",
    "Strange Dreams": "Rêves étranges",
    "Potential: Shared Dream": "Éventualité : rêve partagé",
    "Find A Way To Revisit The Dream": "Trouver un moyen de revivre le rêve",

    # ---------------------------------------------------- the Blake family
    "Blake Family Bloodline": "Lignée de la famille Blake",
    "Blake History": "Histoire des Blake",
    "Blake Manor": "Blake Manor",
    "The Blake Family": "La famille Blake",
    "The End Of The Blakes": "La fin des Blake",
    "The Tale Of Percival Blake": "Le récit de Percival Blake",
    "Investigate Percival Blake": "Enquêter sur Percival Blake",
    "Percy Blake Painting": "Portrait de Percy Blake",
    "Walter Blake Paintings": "Portraits de Walter Blake",
    "Henry Blake Photographs": "Photographies de Henry Blake",
    "Atrium Family Painting": "Portrait de famille de l’atrium",
    "Blake Residence Family Painting": "Portrait de famille de la résidence Blake",
    "Shrine To Mary Blake": "Autel dédié à Mary Blake",
    "Crippled Young Master": "Le jeune maître infirme",
    "Deceased Marchioness": "La marquise défunte",
    "Idolised Wife": "Épouse idolâtrée",
    "Wife Recently Deceased": "Épouse récemment décédée",
    "A Third Bloodline": "Une troisième lignée",
    "Who Is The Third Bloodline": "Qui est la troisième lignée ?",
    "Miss Deane's Bloodline": "La lignée de Mlle Deane",
    "Mister Ó Finn's Bloodline": "La lignée de M. Ó Finn",
    "Land Records": "Registres fonciers",
    "Burial Record": "Acte d’inhumation",
    "Record": "Registre",
    "Crown": "La Couronne",
    "Legacy": "Héritage",
    "A Legacy For Mister Skerritt": "Un héritage pour M. Skerritt",
    "Fall From Grace": "Disgrâce",
    "Philanthropy": "Philanthropie",
    "Wealthy": "Fortuné",
    "Treasure": "Trésor",
    "Treasure Map": "Carte au trésor",
    "Find The Blake Treasure": "Trouver le trésor des Blake",
    "Follow The Treasure Map": "Suivre la carte au trésor",

    # ------------------------------------------------------- places & doors
    "Catacombs": "Catacombes",
    "Chamber": "La Chambre",
    "Gardens": "Jardins",
    "Hedge Maze": "Labyrinthe de haies",
    "Mausoleum": "Mausolée",
    "Nursery": "Chambre d’enfant",
    "Old Well": "Vieux puits",
    "Passageway": "Passage",
    "Secret Laboratory": "Laboratoire secret",
    "Store Room Cage": "Cage de la réserve",
    "East Corridors": "Couloirs est",
    "East Tower": "Tour est",
    "South East Corridor": "Couloir sud-est",
    "East Courtyard Basement Entrance": "Entrée du sous-sol, cour est",
    "South East Basement Entrance": "Entrée du sous-sol, sud-est",
    "Manager's Living Quarters": "Appartements du gérant",
    "Manager's Office": "Bureau du gérant",
    "Chef Office Door": "Porte du bureau du chef",
    "Cook's Office Door": "Porte du bureau de la cuisinière",
    "Hatch Door": "Trappe",
    "Hidden Door": "Porte dérobée",
    "Secret Doorway": "Passage secret",
    "Missing Doorway": "Porte disparue",
    "The Disappeared Door": "La porte disparue",
    "Sealed Door": "Porte scellée",
    "Blocked Path": "Chemin obstrué",
    "Dead End": "Impasse",
    "Repaired Stall Door": "Porte de stalle réparée",
    "Distinct Archway": "Arche singulière",
    "Sun Archway": "Arche du soleil",
    "Wine Cellar Lock": "Serrure de la cave à vin",
    "Room 2": "Chambre 2",
    "Room 7": "Chambre 7",
    "Room 15": "Chambre 15",
    "Room 21": "Chambre 21",
    "Miss Deane's Room": "La chambre de Mlle Deane",
    "Empty Bedroom": "Chambre vide",
    "Room Assignments": "Attribution des chambres",

    # ----------------------------------------------------------------- keys
    "Atrium Key": "Clé de l’atrium",
    "Basement Entrance Key ": "Clé de l’entrée du sous-sol ",
    "Basement Key Chain": "Trousseau du sous-sol",
    "Blake Residence Key": "Clé de la résidence Blake",
    "Catacomb Key": "Clé des catacombes",
    "D'Arcy's Room Key": "Clé de la chambre D’Arcy",
    "Locker Key": "Clé du casier",
    "Manager's Quarters Key": "Clé des appartements du gérant",
    "Men's Dormitory Key": "Clé du dortoir des hommes",
    "Missus Lau's Key": "Clé de Mme Lau",
    "North East Corridor Key": "Clé du couloir nord-est",
    "North West Corridor Key ": "Clé du couloir nord-ouest ",
    "Old Rusty Key": "Vieille clé rouillée",
    "Room 11 Key": "Clé de la chambre 11",
    "Room 19 Key": "Clé de la chambre 19",
    "South East Corridor Key": "Clé du couloir sud-est",
    "South West Corridor Key": "Clé du couloir sud-ouest",
    "Staff Key": "Clé du personnel",
    "Women's Dormitory Key": "Clé du dortoir des femmes",
    "A Note On Master Keys": "Une note sur les passe-partout",
    "Find The Key": "Trouver la clé",
    "Use The Key": "Se servir de la clé",

    # ------------------------------------------------------------- documents
    "Badly Written Note": "Note mal rédigée",
    "Blackmail Envelope": "Enveloppe de chantage",
    "Blackmail Letter": "Lettre de chantage",
    "Book Of Irish Gods": "Livre des dieux d’Irlande",
    "Book On Housekeeping": "Manuel de tenue de maison",
    "Burnt Paper": "Papier brûlé",
    "Cache Of Stolen Documents": "Cache de documents volés",
    "Coat Note": "Note dans un manteau",
    "Code Of Conduct": "Règlement intérieur",
    "Coded Papers": "Papiers chiffrés",
    "Correspondence": "Correspondance",
    "Correspondence With Mister Dupré": "Correspondance avec M. Dupré",
    "Discarded Note": "Note jetée",
    "Entertainment Schedule": "Programme des divertissements",
    "Family Letter": "Lettre de famille",
    "Family Photographs": "Photographies de famille",
    "Firepit Paper": "Papier du foyer",
    "Guest Sign-in Times": "Heures d’arrivée des invités",
    "Hiring Letter": "Lettre d’engagement",
    "Hotel Finances": "Comptes de l’hôtel",
    "Letter From Doctor Callaghan": "Lettre du docteur Callaghan",
    "Letter From Mantovani": "Lettre de Mantovani",
    "Letter From Miss Deane": "Lettre de Mlle Deane",
    "Letter From Mister Skerritt": "Lettre de M. Skerritt",
    "Letter To The Manager": "Lettre au gérant",
    "Letters From Fiadh's Sister-in-law.": "Lettres de la belle-sœur de Fiadh.",
    "List Of Names": "Liste de noms",
    "Lunch Invite": "Invitation à déjeuner",
    "Manor Maps": "Plans du manoir",
    "Map Of Catacombs": "Plan des catacombes",
    "Map Of The Region": "Carte de la région",
    "Medical Certificate": "Certificat médical",
    "Medical Notes On Miss Mantovani": "Notes médicales sur Mlle Mantovani",
    "Miss Deane's Invitation": "Invitation de Mlle Deane",
    "Miss Deane's Journal": "Journal de Mlle Deane",
    "Miss Deane's Leaving Letter": "Lettre de départ de Mlle Deane",
    "Miss Deane's Signature": "Signature de Mlle Deane",
    "Miss McLeod's Diary": "Journal intime de Mlle McLeod",
    "Miss McLeod's Note": "Note de Mlle McLeod",
    "Missing Pages From Miss Deane's Journal": "Pages arrachées du journal de Mlle Deane",
    "Missus Erickon's Notes": "Notes de Mme Erickson",
    "Missus Joyce's Bible": "Bible de Mme Joyce",
    "Missus Lau's Diary": "Journal intime de Mme Lau",
    "Missus Lau's Diary Code": "Chiffre du journal de Mme Lau",
    "Mister D'Arcy's Letters": "Lettres de M. D’Arcy",
    "Mister Doyle's Gnostic Bible": "Bible gnostique de M. Doyle",
    "Mister Dupré's Letter To A Deceased Friend": "Lettre de M. Dupré à un ami défunt",
    "Mister O'Meara's Journal": "Journal de M. O’Meara",
    "Mister Skerritt's Cards": "Cartes de M. Skerritt",
    "Mister Skerritt's Code": "Chiffre de M. Skerritt",
    "Mister Skerritt's Financials": "Comptes de M. Skerritt",
    "Mister Skerritt's Journal": "Journal de M. Skerritt",
    "Mister Skerritt's Will": "Testament de M. Skerritt",
    "Mister Varley's Code": "Chiffre de M. Varley",
    "News Clippings": "Coupures de presse",
    "Note From Mister Varley": "Note de M. Varley",
    "Notes On Missus Erickson": "Notes sur Mme Erickson",
    "Notice Board": "Tableau d’affichage",
    "Old Irish Grimoire": "Vieux grimoire irlandais",
    "Phrenology Book": "Traité de phrénologie",
    "Postal Order": "Mandat postal",
    "Ritual Pages": "Pages du rituel",
    "Scattered Papers": "Papiers épars",
    "Scrap Of Paper": "Bout de papier",
    "Scroll": "Parchemin",
    "Sign In Book": "Registre des arrivées",
    "Staff Rota": "Tableau de service",
    "Strange Bible": "Bible étrange",
    "Talks Schedule": "Programme des conférences",
    "Timetable": "Emploi du temps",
    "Torn Up Letter": "Lettre déchirée",
    "Wanted Poster": "Avis de recherche",
    "Will": "Testament",
    "Wine List": "Carte des vins",
    "Written Complaint": "Plainte écrite",
    "Father Sinnott's Gnostic Bible": "Bible gnostique du père Sinnott",
    "Father Sinnott's Sequence": "La séquence du père Sinnott",
    "Doyle's Sketches": "Croquis de Doyle",
    "Detailed Sketches Of A Vase": "Croquis détaillés d’un vase",
    "Drawings Of A Young Woman": "Dessins d’une jeune femme",
    "Miss Hisham's Drawing Of A Vase": "Dessin d’un vase par Mlle Hisham",
    "Manager's Research On Miss Deane": "Enquête du gérant sur Mlle Deane",
    "O'Connor Family Research": "Recherches sur la famille O’Connor",
    "Regional Research": "Recherches régionales",
    "Gnostic Research": "Recherches gnostiques",
    "Missing Research": "Recherches disparues",
    "History Of The Vase": "Histoire du vase",
    "Telegram For Miss Barbosa": "Télégramme pour Mlle Barbosa",
    "Retrieve The Telegram": "Récupérer le télégramme",

    # ------------------------------------------------------------- objects
    "Alcohol Tinged Glass": "Verre teinté d’alcool",
    "An Old Safe": "Un vieux coffre-fort",
    "Ancient Machine": "Machine ancienne",
    "Apron": "Tablier",
    "Baking Soda": "Bicarbonate de soude",
    "Bottle Of Alcohol": "Bouteille d’alcool",
    "Bottle Of Water": "Bouteille d’eau",
    "Bloody Handkerchiefs": "Mouchoirs ensanglantés",
    "Brooch": "Broche",
    "Bucket": "Seau",
    "Cathal's Lockbox": "Coffret de Cathal",
    "Ceremonial Dagger": "Dague cérémonielle",
    "Chemical Bench": "Paillasse de chimie",
    "Chiave Del Sigillo": "Chiave del Sigillo",
    "Chimney Charm": "Charme de cheminée",
    "Cleaning Solution": "Solution nettoyante",
    "Recipe For A Cleaning Solution": "Recette d’une solution nettoyante",
    "Copper Discs": "Disques de cuivre",
    "Zinc Discs": "Disques de zinc",
    "Paper Discs": "Disques de papier",
    "Discs": "Disques",
    "Voltaic Cells": "Piles voltaïques",
    "Costume Jewellery": "Bijoux de pacotille",
    "Folk Jewellery": "Bijoux populaires",
    "Fine Clothes And Jewellery": "Beaux vêtements et bijoux",
    "Hand-Me-Down Irish Keepsake": "Souvenir irlandais transmis en héritage",
    "Hand-carved Rattle": "Hochet taillé à la main",
    "Headdress": "Coiffe",
    "Embroidered Handkerchief": "Mouchoir brodé",
    "Large Brooch": "Grande broche",
    "Laudanum": "Laudanum",
    "Locket": "Médaillon",
    "Locket Initials": "Initiales du médaillon",
    "Luggage": "Bagages",
    "Luggage Reclaim Ticket: 12": "Bulletin de bagages : 12",
    "Luggage Reclaim Ticket: 46": "Bulletin de bagages : 46",
    "Trunk In Bay 46": "Malle dans la case 46",
    "Mourning Cameo": "Camée de deuil",
    "Murphy Crib": "Berceau des Murphy",
    "Mysterious Object": "Objet mystérieux",
    "Necklace": "Collier",
    "A Crest On A Necklace": "Un blason sur un collier",
    "Near-Empty Bottle": "Bouteille presque vide",
    "Empty Pill Bottle": "Flacon de pilules vide",
    "Sleeping Pills": "Somnifères",
    "Quinine Powder": "Poudre de quinine",
    "Syringe Of Narcotics": "Seringue de narcotiques",
    "Vial Of Blood": "Fiole de sang",
    "Vial Of Poison": "Fiole de poison",
    "Odd Stone": "Pierre singulière",
    "Three Stones": "Trois pierres",
    "Old Anvil": "Vieille enclume",
    "Old Photograph": "Vieille photographie",
    "Ornamental Cane": "Canne d’apparat",
    "Ornate Belt": "Ceinture ouvragée",
    "Parcel Of Money": "Liasse de billets",
    "Mantovani's Money": "L’argent de Mantovani",
    "Retrieve Mantovani's Money": "Récupérer l’argent de Mantovani",
    "Periodic Table Of Elements": "Tableau périodique des éléments",
    "Phrenology Statue": "Buste de phrénologie",
    "Pocket Watch": "Montre de gousset",
    "Possessed Ring": "Bague possédée",
    "Stylised Ring": "Bague stylisée",
    "Salt": "Sel",
    "Screwdriver": "Tournevis",
    "Silk Scarf": "Écharpe de soie",
    "Sketching Materials": "Matériel à dessin",
    "Skull Mask": "Masque de crâne",
    "Slides": "Plaques de projection",
    "Slipper": "Chausson",
    "Spirit Board": "Planche des esprits",
    "Fetch The Spirit Board": "Aller chercher la planche des esprits",
    "Spirit Camera": "Appareil à spectres",
    "Spiral Machine": "Machine en spirale",
    "Strange Device": "Appareil étrange",
    "Strange Materials": "Matériaux étranges",
    "Telegraph Machine, Broken": "Télégraphe, hors d’usage",
    "Telegraph Machine, Fixed": "Télégraphe, réparé",
    "Fix The Telegraph Machine": "Réparer le télégraphe",
    "Turpentine": "Térébenthine",
    "Typewriter": "Machine à écrire",
    "Urn": "Urne",
    "Vats": "Cuves",
    "The Vase Of Nectanebo": "Le vase de Nectanébo",
    "Well-Worn Tarot Deck": "Jeu de tarot bien usé",
    "White Heather Hairpin": "Épingle à cheveux en bruyère blanche",
    "Suspicious Lockbox": "Coffret suspect",
    "Men's Dormitory Lockbox": "Coffret du dortoir des hommes",
    "Women's Dormitory Lockbox": "Coffret du dortoir des femmes",
    "Miss McLeod's Lockbox": "Coffret de Mlle McLeod",
    "Missus Lau's Box": "Coffret de Mme Lau",
    "Missus Lau's Dagger": "Dague de Mme Lau",
    "Mister Ó Finn's Bag": "Sac de M. Ó Finn",
    "Open Locked Box": "Ouvrir le coffret verrouillé",
    "Doctor Callaghan's Components": "Composants du docteur Callaghan",
    "Miss Callaghan's Components": "Composants de Mlle Callaghan",
    "Find More Components": "Trouver d’autres composants",
    "Miss Hisham's Melody": "La mélodie de Mlle Hisham",
    "Find Hypnotic Music": "Trouver la musique hypnotique",
    "Find Where To Play The Melody": "Trouver où jouer la mélodie",
    "Photo Of Eamonn Ward": "Photo d’Eamonn Ward",
    "Photograph Of Miss Deane": "Photographie de Mlle Deane",
    "Photograph Of The Murphy Child": "Photographie de l’enfant Murphy",
    "Painting Of Deane": "Portrait de Deane",
    "Forged Paintings": "Tableaux contrefaits",

    # ---------------------------------------------------- marks, traces, tells
    "Averted Gaze": "Regard fuyant",
    "Discerning Gaze": "Regard pénétrant",
    "Boot Prints": "Empreintes de bottes",
    "Footprints": "Empreintes de pas",
    "Burnt Symbols": "Symboles brûlés",
    "Ritual Markings": "Marques rituelles",
    "Ink-Blotted Symbols": "Symboles maculés d’encre",
    "Scratched-Out Symbols": "Symboles rayés",
    "Shaky Symbols": "Symboles tremblés",
    "Mysterious Symbol": "Symbole mystérieux",
    "Well Symbols": "Symboles du puits",
    "Symbolic Code": "Code symbolique",
    "Sigil": "Sceau",
    "Ticket Sigil": "Sceau du billet",
    "Charcoal-Smudged Hands": "Mains tachées de fusain",
    "Powder Stain": "Tache de poudre",
    "Cigar Stains": "Taches de cigare",
    "Cigar Burn On Chair": "Brûlure de cigare sur un fauteuil",
    "Stained Hands": "Mains tachées",
    "Raw Hands": "Mains à vif",
    "Shaky Hands": "Mains tremblantes",
    "Shakes": "Tremblements",
    "Scars On Hands And Face": "Cicatrices aux mains et au visage",
    "Small Burn Scars": "Petites cicatrices de brûlure",
    "Scarring": "Cicatrices",
    "Curious Tattoo": "Tatouage curieux",
    "Tan Line": "Marque de hâle",
    "Windburnt Skin": "Peau brûlée par le vent",
    "Deathly Pallor": "Pâleur cadavérique",
    "Sunken Eyes": "Yeux cernés",
    "Sunken, Red Eyes": "Yeux cernés et rougis",
    "Tired Eyes": "Yeux fatigués",
    "Long Red Hair": "Longs cheveux roux",
    "Unusual Hair Colour": "Couleur de cheveux inhabituelle",
    "Wild Hair And Beard": "Cheveux et barbe en broussaille",
    "Crack In Glasses": "Fêlure dans les lunettes",
    "Erased Lines": "Lignes effacées",
    "Fake Handwriting": "Écriture contrefaite",
    "Name Mismatch": "Discordance de nom",
    "Circled Numbers": "Nombres entourés",
    "Debris": "Débris",
    "Remains": "Restes",
    "Dusty Clothes": "Vêtements poussiéreux",
    "Patched Up Clothing": "Vêtements rapiécés",
    "Outdoor Working Clothes": "Vêtements de travail d’extérieur",
    "Recently Altered Dress": "Robe récemment retouchée",
    "Foreign Fashion Mixed With Local": "Mode étrangère mêlée au costume local",
    "Well Dressed": "Bien mis",
    "The Shawl": "Le châle",
    "Notebook In Pocket": "Carnet dans une poche",
    "Pen In Pocket": "Plume dans une poche",
    "Hand On Pocket Watch": "Main sur la montre de gousset",

    # ------------------------------------------------------ bearing & manner
    "Eager Pose": "Attitude empressée",
    "Innocent Bearing": "Air innocent",
    "Proud Stature": "Port altier",
    "Knowing Smile": "Sourire entendu",
    "Nervous Energy": "Énervement fébrile",
    "Tense Shoulders": "Épaules crispées",
    "Tired Shoulders": "Épaules lasses",
    "Cold Dead Shoulder": "Épaule froide et morte",
    "Distracted Look In Eyes": "Regard absent",
    "Unhappy Expression": "Air malheureux",
    "Watchful Expression": "Air aux aguets",
    "Disdain": "Dédain",
    "Longing": "Nostalgie",
    "Refusal": "Refus",
    "Rejected Request": "Requête rejetée",
    "Recognition": "Reconnaissance",
    "Identity Known": "Identité connue",
    "Thrill Seeker": "Amateur de sensations",
    "Walks Leaning On A Cane": "Marche appuyé sur une canne",
    "Scent Of Oats And Sugar": "Odeur d’avoine et de sucre",
    "No Family": "Sans famille",
    "No Fraternity": "Sans confrérie",
    "No Mementos": "Aucun souvenir",
    "Her Family": "Sa famille",
    "Family Provider": "Soutien de famille",
    "A Fondness For The Library": "Un penchant pour la bibliothèque",
    "Adoration Of The Staff": "L’adoration du personnel",
    "Chaperoning": "Chaperonnage",
    "Bad Blood": "Rancune",
    "Their Relationship": "Leur relation",
    "What’s The Nature Of Their Relationship?": "Quelle est la nature de leur relation ?",
    "Marriage Plans": "Projets de mariage",
    "Travel Plans": "Projets de voyage",
    "Clandestine Meeting": "Rendez-vous clandestin",
    "Reason For Argument": "Motif de la dispute",
    "Intent To Harm": "Intention de nuire",
    "Kidnapping": "Enlèvement",
    "Kidnapper Lost": "Le ravisseur a disparu",
    "Suicide": "Suicide",
    "Fraud": "Imposture",
    "Proof": "Preuve",
    "Confession: Missus Erickson Is A Fraud": "Aveu : Mme Erickson est une imposteuse",
    "Diagnosis": "Diagnostic",
    "Medical Code U0.33": "Code médical U0.33",
    "Discover Meaning Of Medical Code": "Découvrir le sens du code médical",
    "Doyle's Doping": "Le dopage de Doyle",
    "Drugged Water Jug": "Carafe d’eau droguée",
    "What Are The Drugs For?": "À quoi servent ces drogues ?",
    "Dwindling Resources": "Ressources déclinantes",
    "Carriage Accident": "Accident de voiture",
    "Dead Reverend": "Le révérend mort",
    "Missing People": "Personnes disparues",
    "Miss Deane Is Alive": "Mlle Deane est vivante",
    "Miss Deane Is Dead": "Mlle Deane est morte",
    "Mister Ó Finn Is Alive": "M. Ó Finn est vivant",
    "Mister Ó Finn Is Dead": "M. Ó Finn est mort",
    "Miss Mantovani Lives": "Mlle Mantovani est vivante",
    "Miss Mantovani's Death": "La mort de Mlle Mantovani",
    "Miss Mantovani's Health": "La santé de Mlle Mantovani",
    "Skerritt's Fate": "Le sort de Skerritt",
    "Already Eliminated": "Déjà écarté",
    "End Of The Line": "Fin de la lignée",
    "See Father": "Voir son père",
    "Signs Of Child's Play": "Traces de jeux d’enfant",
    "Mysterious Crest On Necktie": "Blason mystérieux sur une cravate",
    "Ritual Impact": "Conséquences du rituel",
    "Ivy's Request For Help": "L’appel à l’aide d’Ivy",
    "Mister Doyle's Request": "La requête de M. Doyle",
    "Mister Dupré's Deceased Friend": "L’ami défunt de M. Dupré",
    "Mister Skerritt's Reading": "La lecture de M. Skerritt",
    "Missus Erickson's Intentions": "Les intentions de Mme Erickson",
    "Miss Deane's Sparring Partner": "Le partenaire d’escrime de Mlle Deane",
    "Miss Deane's Wanderings": "Les allées et venues de Mlle Deane",
    "Guest Alibis": "Alibis des invités",
    "Resident Alibis": "Alibis des résidents",
    "The Guests": "Les invités",
    "Staff": "Personnel",
    "The Staff": "Le personnel",
    "Babelstone": "Babelstone",
    "Journal Of Mister Dupré": "Journal de M. Dupré",
    "Bridge Game": "Partie de bridge",
    "Bridge Game Attendees": "Participants à la partie de bridge",
    "Hedonistic Ball": "Bal licencieux",
    "Sunday Delivery": "Livraison du dimanche",
    "Basement Opportunities": "Occasions au sous-sol",
    "Coventry: Magical Fabrication": "Coventry : fabrication magique",
    "Connection Between Father Sinnott And Mister Doyle": "Lien entre le père Sinnott et M. Doyle",
    "Sinnott: Seamus Doyle": "Sinnott : Seamus Doyle",
    "How Does Miss Deane Know Miss Barbosa?": "Comment Mlle Deane connaît-elle Mlle Barbosa ?",
    "What Do The Symbols Mean?": "Que signifient ces symboles ?",
    "What Does 451 Mean?": "Que signifie 451 ?",
    "What's In The Safe?": "Qu’y a-t-il dans le coffre ?",
    "What's In The Stables' Safe?": "Qu’y a-t-il dans le coffre des écuries ?",
    "Find The Safe Code": "Trouver la combinaison du coffre",
    "Signs Of A Trail": "Traces d’un passage",
    "Well Scrying": "Divination par le puits",
    "Protect The Well": "Protéger le puits",
    "Apprehend The Suspect": "Appréhender le suspect",
    "Discover The Truth": "Découvrir la vérité",
    "Decipher Note": "Déchiffrer la note",
    "Read The Verse": "Lire le verset",
    "Check In": "S’enregistrer",
    "Check Ticket": "Vérifier le billet",
    "Dupre: Check Ticket": "Dupré : vérifier le billet",
    "Search For Change": "Chercher de la monnaie",
    "9pm Tuesday 26th October": "Mardi 26 octobre, 21 h",
    "1583": "1583",
    "The Letter 'P'": "La lettre « P »",
    "The Letter 'S'": "La lettre « S »",
    "The Letter 'Y'": "La lettre « Y »",
    "The Battle Of Tailtiu": "La bataille de Tailtiu",
    "Fascination With Vase": "Fascination pour le vase",
    "Research The Vase": "Se documenter sur le vase",

    # ------------------------------------------------------------- the tasks
    "Ask About His Strange Equipment": "S’enquérir de son étrange équipement",
    "Ask About Miss Deane": "S’enquérir de Mlle Deane",
    "Ask About The Shadowy Figure": "S’enquérir de la silhouette dans l’ombre",
    "Ask About Tír Na NÓg": "S’enquérir de Tír Na NÓg",
    "Ask Residents About Their Dreams": "Interroger les résidents sur leurs rêves",
    "Ask Who Wore The Skull Mask": "Demander qui portait le masque de crâne",
    "Attend The Silent Dinner": "Assister au dîner silencieux",
    "Go To The Silent Dinner": "Se rendre au dîner silencieux",
    "Meet Blake For Lunch": "Retrouver Blake pour le déjeuner",
    "Talk To Master Blake": "Parler au jeune maître Blake",
    "Talk With Missus Erickson": "S’entretenir avec Mme Erickson",
    "Trying To Talk With Priest": "Tenter de parler au prêtre",
    "Interrogate Mister O'Meara!": "Interroger M. O’Meara !",
    "Pass On Mister Doyle's Message": "Transmettre le message de M. Doyle",
    "Show Mister Toussaint's Notes": "Montrer les notes de M. Toussaint",
    "Show Photograph To Father Sinnott": "Montrer la photographie au père Sinnott",
    "Tell Mister Toussaint About The Confession": "Parler de l’aveu à M. Toussaint",
    "Understand Miss McLeod's Actions": "Comprendre les agissements de Mlle McLeod",
    "Learn About The Quinn Family History": "Se renseigner sur l’histoire des Quinn",
    "Learn Shay's Full Name": "Apprendre le nom complet de Shay",
    "Learn The Name Of An Angel": "Apprendre le nom d’un ange",
    "Find A Way": "Trouver un moyen",
    "Find A Way To Show Murphy Her Child": "Trouver un moyen de montrer son enfant à Murphy",
    "Find And Return The Blackmail Material": "Retrouver et rendre les pièces du chantage",
    "Find Charms": "Trouver les charmes",
    "Find Correspondence": "Trouver la correspondance",
    "Find Deane's Letter": "Trouver la lettre de Deane",
    "Find Her Book": "Trouver son livre",
    "Find Miss Deane's Departure Letter": "Trouver la lettre de départ de Mlle Deane",
    "Find Miss Deane's Hidden Notes": "Trouver les notes cachées de Mlle Deane",
    "Find Miss Deane's Room": "Trouver la chambre de Mlle Deane",
    "Find Something Of Mister D'Arcy's": "Trouver un objet appartenant à M. D’Arcy",
    "Find The Body Of Water": "Trouver l’étendue d’eau",
    "Gain Entry To The Basement": "Pénétrer dans le sous-sol",
    "Gain Entry To The Office": "Pénétrer dans le bureau",
    "Explore Manager's Office": "Explorer le bureau du gérant",
    "Explore The Catacombs": "Explorer les catacombes",
    "Follow The Trail Through The Gardens": "Suivre la piste à travers les jardins",
    "Follow The Trail Through The Manor": "Suivre la piste à travers le manoir",
    "Follow The Trail Through The Maze": "Suivre la piste à travers le labyrinthe",
    "Retrieve Object From Vent": "Récupérer l’objet dans la bouche d’aération",
    "Return To The Ladies Bathroom": "Retourner aux toilettes des dames",
    "Stop Coventry's Ritual!": "Arrêter le rituel de Coventry !",
    "Stop The Ritual!": "Arrêter le rituel !",
    "Search Her Station": "Fouiller son poste de travail",
    "Search The Hedge Maze For Signs Of The Entity": "Chercher des traces de l’Entité dans le labyrinthe",
    "Search The Kitchen": "Fouiller la cuisine",
    "Search The Laundry": "Fouiller la buanderie",
    "Search The Manager's Living Quarters": "Fouiller les appartements du gérant",
    "Search The Manager's Office": "Fouiller le bureau du gérant",
    "Search The Manager's Quarters": "Fouiller les quartiers du gérant",
    "Search The Men's Dormitory": "Fouiller le dortoir des hommes",
    "Search The Room": "Fouiller la chambre",
    "Search The Servants' Hall": "Fouiller la salle des domestiques",
    "Search The Sleeping Quarters": "Fouiller les dortoirs",
    "Search The Store Room": "Fouiller la réserve",
    "Search The Wine Cellar": "Fouiller la cave à vin",
    "Search The Women's Dormitory": "Fouiller le dortoir des femmes",
    "Investigate Miss Murphy's Quarters": "Enquêter sur les quartiers de Mlle Murphy",
    "Investigate Missus Joyce's Quarters": "Enquêter sur les quartiers de Mme Joyce",
    "Investigate Mister Doyle's Quarters": "Enquêter sur les quartiers de M. Doyle",
    "Investigate Mister Hunter's Quarters": "Enquêter sur les quartiers de M. Hunter",
    "Investigate Mister Varley's Office": "Enquêter sur le bureau de M. Varley",
    "Investigate Mister Varley's Quarters": "Enquêter sur les quartiers de M. Varley",
    "Investigate Research Station": "Enquêter sur le poste de recherche",
    "Investigate The Basement": "Enquêter sur le sous-sol",
    "Investigate The Blake Residence": "Enquêter sur la résidence Blake",
    "Investigate The Burnt Symbols": "Enquêter sur les symboles brûlés",
    "Investigate The Firepit": "Enquêter sur le foyer",
    "Investigate The Living Quarters": "Enquêter sur les quartiers d’habitation",
    "Investigate The Mausoleum": "Enquêter sur le mausolée",
    "Investigate The Stables": "Enquêter sur les écuries",
    "Investigate The Well": "Enquêter sur le puits",
    "Research Gnosticism": "Se documenter sur le gnosticisme",
    "Research Irish Mythology": "Se documenter sur la mythologie irlandaise",
    "Research Lucid Dreaming": "Se documenter sur le rêve lucide",
    "Research Milesians": "Se documenter sur les Milésiens",
    "Research Smithing In The Book Of The Gods": "Se documenter sur la forge dans le Livre des dieux",
    "Research The Fate Of The Old Gods": "Se documenter sur le sort des anciens dieux",
    "Research The Old Gods": "Se documenter sur les anciens dieux",
    "Research The Secret Of The Staff": "Se documenter sur le secret du personnel",
    "Research Translation": "Se documenter sur la traduction",
    "Research Tír Na NÓg": "Se documenter sur Tír Na NÓg",
}

# "Investigate Room N" — generated so the numbering can never drift out of sync.
for _n in (1, 3, 5, 6, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22):
    EVIDENCE[f"Investigate Room {_n}"] = f"Enquêter sur la chambre {_n}"

# "Profile X" and "Reflection: X" — one table each, same person list.
_PEOPLE = {
    "Doctor Callaghan": "le docteur Callaghan",
    "Father Sinnott": "le père Sinnott",
    "Master Blake": "le jeune maître Blake",
    "Miss Barbosa": "Mlle Barbosa",
    "Miss Callaghan": "Mlle Callaghan",
    "Miss Hisham": "Mlle Hisham",
    "Miss Mantovani": "Mlle Mantovani",
    "Miss McLeod": "Mlle McLeod",
    "Miss Murphy": "Mlle Murphy",
    "Miss Quinn": "Mlle Quinn",
    "Missus D'Arcy": "Mme D’Arcy",
    "Missus Erickson": "Mme Erickson",
    "Missus Joyce": "Mme Joyce",
    "Missus Lau": "Mme Lau",
    "Mister Coventry": "M. Coventry",
    "Mister Doyle": "M. Doyle",
    "Mister Dupré": "M. Dupré",
    "Mister Hunter": "M. Hunter",
    "Mister O'Meara": "M. O’Meara",
    "Mister Skerritt": "M. Skerritt",
    "Mister Toussaint": "M. Toussaint",
    "Mister Varley": "M. Varley",
    "Mister Ó Finn": "M. Ó Finn",
    "The Marquess": "le marquis",
}
# Master Blake, Mister Coventry, Mister Ó Finn and the Marquess can be profiled
# but have no Reflection node.
_NO_REFLECTION = {"Master Blake", "Mister Coventry", "Mister Ó Finn", "The Marquess"}

for _en, _fr in _PEOPLE.items():
    EVIDENCE[f"Profile {_en}"] = f"Profiler {_fr}"
    if _en not in _NO_REFLECTION:
        # Reflection labels keep the colon form and capitalise the person.
        EVIDENCE[f"Reflection: {_en}"] = "Réflexion : " + (_fr[0].upper() + _fr[1:])

for _en, _fr in {
    "Mister Doyle": "M. Doyle", "Mister Dupré": "M. Dupré", "Mister Hunter": "M. Hunter",
    "Mister Toussaint": "M. Toussaint", "Mister Varley": "M. Varley",
}.items():
    EVIDENCE[f"Statement: {_en}"] = f"Déposition : {_fr}"

EVIDENCE.update({
    "Eavesdrop: Miss McLeod And Missus Lau": "Écouter : Mlle McLeod et Mme Lau",
    "Eavesdrop: Miss McLeod And Mister Hunter": "Écouter : Mlle McLeod et M. Hunter",
    "Eavesdrop: Missus Erickson And Mister Ó Finn": "Écouter : Mme Erickson et M. Ó Finn",
})

# Labels whose meaning could not be settled from the dialogue and that a player
# should sanity-check in context. Translated on the best available reading.
REVIEW = {
    "Crown": "British Crown vs a physical crown — dialogue only ever means the British Crown.",
    "Adoration Of The Staff": "Staff = personnel throughout the script; reads as devotion to the hotel staff.",
    "Chamber": "The sealed chamber Percival died opening; matches 'Chamber Sigils Found'.",
    "Record": "Generic 'registre'; sits beside 'Burial Record' and 'Land Records'.",
    "Mistress": "Rendered 'Maîtresse' — could be mistress-of-the-house or a lover.",
}
