#!/usr/bin/env python3
"""
The cast / lore panel — Dialogue System *actor* fields, keyed by technical Name.

This is deduction data, not flavour: shoe size, religion, age, whether they were
in mourning, whether they knew Miss Deane beforehand. The player eliminates
suspects by comparing these against the culprit profile, so the wording has to be
consistent field-for-field across all 25 characters — "medium" must always come
out the same way, or the comparison stops reading as a match.

Fields:
  AltName / FullName / Title_en   name, full name, role
  SocialClass / ArrivalTime / RoomNumber
  castBio / hasNotTalkedWithBio   the two states of the cast card
  Lore1..15_en                    the profile facts

The injector writes both the base field and its " fr" variant, because the lore
panel reads LookupValue and the dialogue UI reads LookupLocalizedValue.
"""

# ------------------------------------------------------------- shared wording
SHOE = {
    "medium": "Ses chaussures sont de taille moyenne.",
    "medium_f": "Ses chaussures sont de taille moyenne.",
    "small": "Elle chausse petit.",
    "large": "Ses bottes sont plutôt grandes.",
}
NOT_TALKED = "\nNous n’avons pas encore parlé. "

_FAITH = {
    "Catholic_m": "Il est catholique.", "Catholic_f": "Elle est catholique.",
    "Protestant_m": "Il est protestant.", "Protestant_f": "Elle est protestante.",
    "Pagan_m": "Il est païen.", "Pagan_f": "Elle est païenne.",
}

ACTORS = {
    # ---------------------------------------------------------------- Ward
    "Ward": {
        "AltName": "M. Ward", "FullName": "Declan Ward",
        "SocialClass": "Classe ouvrière", "ArrivalTime": "30 octobre", "RoomNumber": "4",
    },
    "Choice": {"AltName": "Détective Ward", "FullName": "Declan Ward"},
    "Decision": {"AltName": "Détective Ward", "FullName": "Declan Ward"},
    "Eamonn": {"AltName": "Eamonn Ward"},

    # ------------------------------------------------------------- the cast
    "DArcy": {
        "AltName": "Mme D’Arcy", "FullName": "Olivia D’Arcy",
        "SocialClass": "Haute bourgeoisie", "ArrivalTime": "24 octobre", "RoomNumber": "13",
        "castBio": "Une femme de lettres anglaise au caractère acéré.",
        "hasNotTalkedWithBio": "Une Anglaise qui a un goût prononcé pour le jaune moutarde. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé divers écrits d’elle dans sa chambre.",
        "Lore2_en": "Elle est ici sous une fausse identité et ne peut user de magie.",
        "Lore3_en": SHOE["medium_f"],
        "Lore4_en": _FAITH["Protestant_f"],
        "Lore5_en": "Elle n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore6_en": "Elle n’était jamais venue dans cette région.",
        "Lore8_en": "Elle a tué son mari et ne le pleure pas. ",
        "Lore9_en": "Elle approche de la trentaine.",
        "Lore10_en": "Une fiole de poison à moitié vide se trouve dans sa chambre.",
        "Lore13_en": "MOBILE : Mlle Deane était la maîtresse de M. D’Arcy.",
    },
    "Dupré": {
        "AltName": "M. Dupré", "FullName": "Lloyd Dupré",
        "SocialClass": "Haute bourgeoisie", "ArrivalTime": "23 octobre", "RoomNumber": "11",
        "castBio": "Un ordonnateur de pompes funèbres de La Nouvelle-Orléans.",
        "hasNotTalkedWithBio": "Un homme noir fort bien mis. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé dans le hall une lettre de sa main.",
        "Lore2_en": "Je l’ai vu accomplir des rites magiques.",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": "Il est oungan vaudou.",
        "Lore5_en": "Il n’était jamais venu de ce côté du monde. ",
        "Lore6_en": "Il pleure la perte récente d’une amie.",
        "Lore7_en": "Il n’avait jamais rencontré Mlle Deane avant cette réception.",
        "Lore8_en": "Sa chambre contient des dessins d’un réalisme saisissant.",
        "Lore9_en": "La petite cinquantaine.",
        "Lore11_en": "J’ai trouvé des écrits de lui dans sa chambre. ",
        "Lore13_en": "MOBILE : il veut placer l’âme de son amie dans le corps de Mlle Deane.",
    },
    "Skerritt": {
        "AltName": "M. Skerritt", "FullName": "Michael Skerritt",
        "SocialClass": "Aristocratie", "ArrivalTime": "23 octobre", "RoomNumber": "18",
        "castBio": "Un gentleman de vieille fortune, à l’hiver de sa vie. ",
        "hasNotTalkedWithBio": "Un homme âgé, monocle et canne." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé des lettres de lui adressées à Mlle Deane.",
        "Lore2_en": "Ses tentatives d’apprendre la magie ont échoué. ",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": _FAITH["Protestant_m"],
        "Lore5_en": "Il connaissait Mlle Deane avant son arrivée au manoir.",
        "Lore9_en": "Je lui donne un peu plus de soixante-dix ans.",
        "Lore11_en": "J’ai trouvé divers écrits dans sa chambre.",
        "Lore13_en": "MOBILE : il a envoyé à Mlle Deane une lettre de menaces.",
    },
    "Varley": {
        "AltName": "M. Varley", "FullName": "Vincent Varley", "Title_en": "Gérant",
        "SocialClass": "Classe ouvrière (personnel)", "RoomNumber": "Quartiers du gérant",
        "castBio": "Le gérant de l’hôtel, en dépit de son abord peu engageant.",
        "hasNotTalkedWithBio": "Le gérant de l’hôtel." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé divers écrits de sa main.",
        "Lore4_en": _FAITH["Catholic_m"],
        "Lore5_en": "Il est le gérant et connaît bien le domaine.",
        "Lore6_en": "Il n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore7_en": "Il enquêtait lui aussi sur Mlle Deane.",
        "Lore9_en": "Il a dans les quarante-cinq ans.",
    },
    "Caitlin": {
        "AltName": "Mme Joyce", "FullName": "Caitlin Joyce", "Title_en": "Gouvernante",
        "SocialClass": "Classe ouvrière (personnel)", "RoomNumber": "Dortoir des femmes",
        "castBio": "La gouvernante de l’hôtel, catholique fervente.",
        "hasNotTalkedWithBio": "La gouvernante." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé ses écrits dans la salle des domestiques.",
        "Lore2_en": "Elle est opposée à la séance et à toute pratique magique.",
        "Lore3_en": "J’ai trouvé des chaussures de taille moyenne dans ses quartiers.",
        "Lore4_en": _FAITH["Catholic_f"],
        "Lore5_en": "Faisant partie du personnel, elle sait se repérer dans le manoir.",
        "Lore6_en": "Elle pleure la perte de son mari.",
        "Lore8_en": "Elle n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore9_en": "Elle vient d’avoir cinquante ans.",
        "Lore13_en": "MOBILE : elle se croit tenue par les Écritures d’éradiquer les praticiens de la magie.",
    },
    "Corentine": {
        "AltName": "Mlle Quinn", "FullName": "Corentine Quinn",
        "SocialClass": "Aristocratie", "ArrivalTime": "23 octobre", "RoomNumber": "14",
        "castBio": "Une aristocrate anglaise, chef de sa maison.",
        "hasNotTalkedWithBio": "Une jeune femme au regard plus vieux que son âge. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé un recueil de ses poèmes.",
        "Lore2_en": "Je l’ai vue accomplir un rituel.",
        "Lore3_en": "Elle porte des bottines de taille moyenne.",
        "Lore4_en": _FAITH["Protestant_f"],
        "Lore5_en": "Elle connaissait Mlle Deane avant son arrivée.",
        "Lore6_en": "Elle pleure la perte de nombreux membres de sa famille.",
        "Lore8_en": "J’ai trouvé dans sa chambre des dessins très caricaturaux.",
        "Lore9_en": "Elle approche de la trentaine.",
        "Lore13_en": "MOBILE : Mlle Deane s’est servie de Mlle Quinn puis l’a écartée pour servir ses propres fins.",
    },
    "Arwa": {
        "AltName": "Mlle Hisham", "FullName": "Arwa Hisham",
        "SocialClass": "Petite bourgeoisie", "ArrivalTime": "24 octobre ", "RoomNumber": "12",
        "castBio": "Une archéologue venue d’Égypte.",
        "hasNotTalkedWithBio": "Une grande femme à la peau brune. " + NOT_TALKED,
        "Lore1_en": "Elle a été invitée au manoir par Mlle Deane.",
        "Lore2_en": "J’ai trouvé des écrits en anglais dans sa chambre.",
        "Lore3_en": "Il y a dans sa chambre des chaussures de taille moyenne.",
        "Lore4_en": "Elle est musulmane sunnite.",
        "Lore5_en": "Elle dessine des plans du domaine.",
        "Lore8_en": "Sa chambre contient du matériel à dessin.",
        "Lore9_en": "Elle a un peu plus de trente ans.",
    },
    "Carmela": {
        "AltName": "Mlle Mantovani", "FullName": "Carmela Mantovani", "Title_en": "La voyante",
        "SocialClass": "Petite bourgeoisie", "ArrivalTime": "25 octobre", "RoomNumber": "5",
        "castBio": "Le médium d’honneur de cette réception ; c’est elle qui conduira la Grande Séance.",
        "hasNotTalkedWithBio": "Le médium qui préside l’événement principal. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé à l’hôtel un livre écrit par elle.",
        "Lore2_en": "C’est une mystique renommée, qui dirige la séance.",
        "Lore3_en": "Les bottines de sa chambre sont de taille moyenne.",
        "Lore4_en": _FAITH["Catholic_f"],
        "Lore7_en": "Elle a évité tout rapport avec Mlle Deane.",
        "Lore9_en": "Elle approche de la quarantaine.",
        "Lore10_en": "Elle va mourir très bientôt.",
    },
    "Cathal": {
        "AltName": "M. O’Meara", "FullName": "Cathal O’Meara",
        "SocialClass": "Aristocratie", "ArrivalTime": "25 octobre ", "RoomNumber": "16",
        "castBio": "Un libertin insouciant du sud de Dublin.",
        "hasNotTalkedWithBio": "Un homme à la canne, d’un abord distant. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé des notes dans son journal, dans sa chambre.",
        "Lore2_en": "Il possède de quoi communier avec les anges.",
        "Lore3_en": "Ses chaussures sont nettement déformées par sa démarche appuyée sur une canne.",
        "Lore4_en": _FAITH["Catholic_m"],
        "Lore5_en": "Il a jadis demandé Mlle Deane en mariage.",
        "Lore6_en": "Il a un passé commun avec Mlle Deane.",
        "Lore8_en": "Sa chambre contient de beaux croquis représentant quelque chose d’horrible.",
        "Lore9_en": "Je lui donne un peu plus de vingt ans.",
        "Lore10_en": "J’ai trouvé dans sa chambre un tableau glaçant, encore inachevé.",
        "Lore13_en": "MOBILE : Mlle Deane a publiquement repoussé sa demande en mariage.",
    },
    "Saoirse": {
        "AltName": "Mlle Murphy", "FullName": "Saoirse Murphy", "Title_en": "Cuisinière",
        "SocialClass": "Classe ouvrière (personnel)", "RoomNumber": "Dortoir des femmes",
        "castBio": "La cuisinière. Une jeune fille timide.",
        "hasNotTalkedWithBio": "La cuisinière." + NOT_TALKED,
        "Lore1_en": "Le billet qu’elle a signé montre qu’elle ne sait pas écrire.",
        "Lore2_en": "Mlle Deane avait commencé à lui enseigner la magie. ",
        "Lore3_en": "Elle chausse petit.",
        "Lore4_en": _FAITH["Catholic_f"],
        "Lore5_en": "Faisant partie du personnel, elle connaît bien le domaine.",
        "Lore7_en": "Elle n’avait rencontré Mlle Deane que depuis peu.",
        "Lore9_en": "Elle a tout juste vingt ans.",
        "Lore11_en": "Elle sait lire, mais pas écrire. ",
    },
    "Darragh": {
        "AltName": "M. Hunter", "FullName": "Darragh Hunter", "Title_en": "Maître d’écurie",
        "SocialClass": "Classe ouvrière (personnel)", "RoomNumber": "Dortoir des hommes",
        "castBio": "Le maître d’écurie et jardinier écossais de l’hôtel. ",
        "hasNotTalkedWithBio": "Le maître d’écurie et jardinier de l’hôtel." + NOT_TALKED,
        "Lore1_en": "C’est lui qui tient le registre de santé des chevaux.",
        "Lore2_en": "Il sait confectionner des charmes.",
        "Lore3_en": "Ses bottes sont plutôt grandes.",
        "Lore5_en": "Faisant partie du personnel, il connaît le manoir et le domaine.",
        "Lore6_en": "Il n’a aucun passé avec Mlle Deane.",
        "Lore9_en": "Il a dans les cinquante-cinq ans.",
        "Lore13_en": "MOBILE : Mlle McLeod l’a supplié de mettre fin à l’assaut psychique de Mlle Deane — par tous les moyens.",
        "Lore14_en": "Signalé comme doué pour la magie dans les notes de Mlle Callaghan. ",
        "Lore15_en": "Son nom figurait sur la liste des praticiens de Mme Erickson, suivi de « ??? ». ",
    },
    "OFinn": {
        "AltName": "M. Ó Finn", "FullName": "Domhnall Ó Finn",
        "SocialClass": "Classe ouvrière", "ArrivalTime": "29 octobre", "RoomNumber": "20",
        "castBio": "Un Voyageur irlandais, protecteur des terres.",
        "hasNotTalkedWithBio": "Un homme à l’allure farouche." + NOT_TALKED,
        "Lore1_en": "Il semble n’écrire qu’en ogham.",
        "Lore2_en": "Son bâton était protégé par la magie, et en contenait.",
        "Lore4_en": _FAITH["Pagan_m"],
        "Lore5_en": "Il connaît bien la région.",
        "Lore6_en": "Il n’a aucun passé avec Mlle Deane.",
        "Lore9_en": "Il paraît avoir dans les quarante ans.",
        "Lore10_en": "Il a été enlevé.",
        "Lore12_en": "Il ne sait ni lire ni écrire l’anglais. ",
        "Lore14_en": "Il a dit à Mme Erickson qu’il ne savait pas écrire l’anglais.",
    },
    "Ettiene": {
        "AltName": "M. Toussaint", "FullName": "Etienne Toussaint",
        "SocialClass": "Haute bourgeoisie", "ArrivalTime": "23 octobre ", "RoomNumber": "6",
        "castBio": "Un universitaire français, pourfendeur de faux mystiques.",
        "hasNotTalkedWithBio": "Un homme aux lunettes remarquables." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé une de ses publications dans la chambre de Mme Erickson.",
        "Lore2_en": "Il ne se fie pas à la magie et n’en use pas.",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": "Il est athée.",
        "Lore5_en": "Il n’a aucun passé avec Mlle Deane.",
        "Lore6_en": "Il n’était jamais venu dans cette région.",
        "Lore9_en": "Il a dans les trente-cinq ans.",
        "Lore15_en": "Son nom a été rayé de la liste des praticiens de Mme Erickson. ",
    },
    "FatherSinnott": {
        "AltName": "Père Sinnott", "FullName": "Lorcan Sinnott",
        "SocialClass": "Petite bourgeoisie", "ArrivalTime": "27 octobre", "RoomNumber": "8",
        "castBio": "Un prêtre catholique d’une grande intensité.",
        "hasNotTalkedWithBio": "Un prêtre." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé des lettres de lui dans la chambre du portier.",
        "Lore2_en": "Il m’a confié un sceau puissant.",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": "C’est un prêtre gnostique.",
        "Lore5_en": "Il possède des plans incomplets du domaine.",
        "Lore6_en": "Il n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore8_en": "Ses tentatives de dessin sont médiocres.",
        "Lore9_en": "Il a dans les soixante-cinq ans.",
        "Lore10_en": "C’est un prêtre catholique.",
        "Lore13_en": "MOBILE : il croyait que Mlle Deane faisait obstacle à sa mission. ",
    },
    "Fiadh": {
        "AltName": "Mlle Callaghan", "FullName": "Fiadh Callaghan",
        "SocialClass": "Classe ouvrière", "ArrivalTime": "26 octobre", "RoomNumber": "9",
        "castBio": "Une femme savante du pays.",
        "hasNotTalkedWithBio": "Une dame d’un certain âge, mise simplement. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé une lettre d’elle dans la chambre du docteur Callaghan.",
        "Lore2_en": "C’est une draoí, une praticienne de la magie.",
        "Lore3_en": "Elle chausse petit.",
        "Lore4_en": _FAITH["Pagan_f"],
        "Lore5_en": "Elle est du pays et connaît bien la région. ",
        "Lore6_en": "Elle connaissait Mlle Deane avant son arrivée au manoir.",
        "Lore9_en": "Elle vient d’avoir cinquante ans.",
        "Lore10_en": "Elle porte une croix d’inspiration celtique.",
        "Lore13_en": "MOBILE : elle craint que Mlle Deane ne lui enlève le docteur Callaghan. ",
        "Lore15_en": "Son nom figurait sur la liste des praticiens de Mme Erickson. ",
    },
    "Hazel": {
        "AltName": "Mme Erickson", "FullName": "Hazel Erickson",
        "SocialClass": "Petite bourgeoisie", "ArrivalTime": "26 octobre", "RoomNumber": "19",
        "castBio": "Un médium américain que M. Toussaint tient pour une imposteuse. ",
        "hasNotTalkedWithBio": "Un médium américain que M. Toussaint tient pour une imposteuse. " + NOT_TALKED,
        "Lore1_en": "Les travaux trouvés dans sa chambre sont couverts de ses annotations.",
        "Lore2_en": "Elle ne peut user de magie.",
        "Lore3_en": "Il y a dans sa chambre des chaussures de taille moyenne.",
        "Lore4_en": _FAITH["Protestant_f"],
        "Lore5_en": "C’était sa première rencontre avec Mlle Deane.",
        "Lore9_en": "Elle a un peu plus de trente ans.",
        "Lore10_en": "Sa chambre est emplie de grimoires et de notes.",
        "Lore11_en": "C’est un médium.",
        "Lore13_en": "MOBILE : le nom de Mlle Deane était entouré sur sa liste de cibles.",
        "Lore14_en": "Les notes de Mlle Callaghan indiquent qu’elle n’a aucun don.",
    },
    "Ines": {
        "AltName": "Mlle Barbosa", "FullName": "Ines Barbosa",
        "SocialClass": "Classe ouvrière", "ArrivalTime": "22 octobre ", "RoomNumber": "17",
        "castBio": "Une Brésilienne en quête de renseignements.",
        "hasNotTalkedWithBio": "Une étrangère vêtue à la mode du pays. " + NOT_TALKED,
        "Lore1_en": "Elle a écrit des télégrammes à l’administration.",
        "Lore3_en": "Ses bottines sont de taille moyenne.",
        "Lore4_en": _FAITH["Catholic_f"],
        "Lore5_en": "Elle n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore6_en": "Elle pleure la perte récente de sa mère.",
        "Lore9_en": "Elle a un peu plus de trente ans.",
        "Lore13_en": "MOBILE : Mlle Deane connaissait la prime offerte pour sa capture",
        "Lore14_en": "Les notes de Mlle Callaghan indiquent qu’elle n’a aucun don.",
    },
    "Ivy": {
        "AltName": "Mlle McLeod", "FullName": "Ivy McLeod",
        "SocialClass": "Aristocratie", "ArrivalTime": "24 octobre ", "RoomNumber": "1",
        "castBio": "Une jeune aristocrate écossaise douée de double vue. ",
        "hasNotTalkedWithBio": "Une jeune femme qui paraît un peu hébétée." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé dans sa chambre un journal empli de ses écrits.",
        "Lore2_en": "Elle possède la double vue.",
        "Lore3_en": "Ses chaussures sont plus petites que la moyenne.",
        "Lore4_en": _FAITH["Protestant_f"],
        "Lore6_en": "Elle connaissait Mlle Deane avant son arrivée au manoir.",
        "Lore9_en": "Elle a un peu plus de vingt ans.",
        "Lore13_en": "MOBILE : Mlle Deane la faisait chanter au sujet de sa liaison avec Mme Lau.",
    },
    "JBlake": {
        "AltName": "Marquis Blake", "FullName": "Jonathan Blake", "Title_en": "Le marquis",
        "SocialClass": "Aristocratie", "RoomNumber": "Résidence Blake",
        "castBio": "Le marquis de Doon. Propriétaire du manoir et hôte de la réception. ",
        "hasNotTalkedWithBio": "Le marquis de Doon, propriétaire de l’hôtel et hôte de la réception. " + NOT_TALKED,
        "Lore1_en": "Sa résidence est couverte de ses divagations.",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": _FAITH["Protestant_m"],
        "Lore5_en": "Il possède le manoir et y a grandi ; il le connaît donc bien.",
        "Lore6_en": "Il pleure sa défunte épouse.",
        "Lore7_en": "Il est sous le même charme que le personnel. ",
        "Lore8_en": "Il n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore9_en": "La petite cinquantaine.",
    },
    "Lan Fen": {
        "AltName": "Mme Lau", "FullName": "Victoria Lau",
        "SocialClass": "Haute bourgeoisie", "ArrivalTime": "24 octobre", "RoomNumber": "3",
        "castBio": "Le chaperon avisé de Mlle McLeod.  ",
        "hasNotTalkedWithBio": "Une dame chinoise au regard perçant. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé dans le hall des lettres de sa main.",
        "Lore2_en": "Elle n’étudie pas la magie.",
        "Lore3_en": "Ses chaussures sont de taille moyenne.",
        "Lore4_en": _FAITH["Protestant_f"],
        "Lore5_en": "Elle connaissait Mlle Deane avant son arrivée au manoir.",
        "Lore6_en": "Elle pleure encore son défunt mari.",
        "Lore9_en": "Elle approche de la trentaine.",
        "Lore11_en": "J’ai trouvé des écrits d’elle dans sa chambre. ",
        "Lore13_en": "MOBILE : Mlle Deane faisait chanter Mlle McLeod au sujet de leur liaison.",
    },
    "Ruairí": {
        "AltName": "Docteur Callaghan", "FullName": "Ruairí Callaghan",
        "SocialClass": "Petite bourgeoisie", "ArrivalTime": "26 octobre", "RoomNumber": "10",
        "castBio": "Un médecin du pays, apprenti en magie, revenu dans la région.",
        "hasNotTalkedWithBio": "Un homme au costume élimé. " + NOT_TALKED,
        "Lore1_en": "J’ai trouvé des lettres de lui adressées à Mlle Deane.",
        "Lore2_en": "C’est un apprenti en magie.",
        "Lore3_en": "Ses chaussures sont de taille moyenne.",
        "Lore4_en": _FAITH["Pagan_m"],
        "Lore5_en": "Il est du pays et connaît bien la région.",
        "Lore6_en": "Il connaissait Mlle Deane avant son arrivée au manoir.",
        "Lore9_en": "Il paraît avoir dans les trente-cinq ans.",
        "Lore10_en": "Il porte une croix.",
        "Lore11_en": "J’ai trouvé des écrits de lui dans sa chambre.",
        "Lore13_en": "MOBILE : Mlle Deane a refusé son offre de lui enseigner la magie.",
        "Lore15_en": "Son nom figurait sur la liste des praticiens de Mme Erickson. ",
    },
    "Doyle": {
        "AltName": "M. Doyle", "FullName": "Seamus Doyle", "Title_en": "Portier",
        "SocialClass": "Classe ouvrière (personnel)", "RoomNumber": "Dortoir des hommes",
        "castBio": "Le portier distrait de l’hôtel. ",
        "hasNotTalkedWithBio": "Le portier de l’hôtel.\nNous n’avons pas encore vraiment parlé. ",
        "Lore1_en": "J’ai trouvé des lettres de lui dans la chambre du père Sinnott. ",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": "Il est lié à la foi gnostique. ",
        "Lore5_en": "Il fait partie du personnel et connaîtrait le domaine.",
        "Lore6_en": "Il n’avait jamais rencontré Mlle Deane avant son arrivée.",
        "Lore8_en": "Il a du matériel à dessin dans ses quartiers.",
        "Lore9_en": "Il approche de la trentaine.",
        "Lore10_en": "Il dessine des plans du domaine.",
        "Lore11_en": "Il porte une croix d’un modèle singulier.",
        "Lore13_en": "MOBILE : il croit que Mlle Deane avait honte d’être vue avec lui.",
    },
    "Coventry": {
        "AltName": "M. Coventry", "FullName": "Simon Coventry",
        "SocialClass": "Haute bourgeoisie", "ArrivalTime": "23 octobre", "RoomNumber": "22",
        "castBio": "Un joaillier vieillissant venu de Londres.",
        "hasNotTalkedWithBio": "Un homme âgé, en costume gris terne." + NOT_TALKED,
        "Lore1_en": "J’ai trouvé des écrits de lui dans sa chambre.",
        "Lore3_en": "Il chausse du moyen.",
        "Lore4_en": _FAITH["Protestant_m"],
        "Lore5_en": "Il a étudié le domaine dans le détail.",
        "Lore7_en": "Cette réception est sa première rencontre avec Mlle Deane.",
        "Lore8_en": "Il a peint dans sa chambre de fort belles pièces.",
        "Lore9_en": "Il me paraît avoir dans les soixante-cinq ans.",
    },
    "WalterBlakeSon": {
        "AltName": "Le jeune maître Blake", "FullName": "Walter Blake", "Title_en": "L’héritier",
        "SocialClass": "Aristocratie", "RoomNumber": "Résidence Blake",
        "castBio": "Le fils du marquis, héritier des terres, du titre et de la fortune. ",
        "hasNotTalkedWithBio": "Le fils du marquis, héritier des terres, du titre et de la fortune. " + NOT_TALKED,
        "Lore1_en": "Il apprend à lire et à écrire en même temps que la cuisinière.",
        "Lore3_en": "Il porte des chaussures d’enfant.",
        "Lore5_en": "Sa chambre offre une belle vue sur le domaine ; il doit bien le connaître. ",
        "Lore6_en": "Il pleure encore la perte de sa mère.",
        "Lore9_en": "Je ne crois pas que le garçon ait même dix ans.",
        "Lore10_en": "Blessé dans l’accident de voiture qui a tué sa mère.",
        "Lore11_en": "Il reste dans sa chambre quand le manoir reçoit des invités.",
        "Lore14_en": "Walter Blake n’existe pas. ",
    },
    "Deane": {
        "AltName": "Mlle Deane", "FullName": "Evelyn Deane",
        "SocialClass": "Aristocratie", "ArrivalTime": "23 octobre", "RoomNumber": "15",
        "castBio": "La femme disparue. Une mondaine dont j’apprends qu’elle avait bien des secrets. Je la sais dans les vingt-cinq ans. ",
        "hasNotTalkedWithBio": "La femme disparue. Une mondaine dont j’apprends qu’elle avait bien des secrets. Je la sais dans les vingt-cinq ans. ",
    },
    "Rev": {
        "AltName": "Révérend Campbell", "FullName": "Charles Campbell",
        "castBio": "Un révérend du pays. Il approche de la soixantaine. ",
        "hasNotTalkedWithBio": "Un révérend du pays. Il approche de la soixantaine. ",
    },
    "Kidnapper": {
        "AltName": "Coupable", "FullName": "Coupable", "Title_en": "Coupable",
        "castBio": "Le coupable de la disparition de Mlle Deane. ",
        "Lore1_en": "Cette personne sait écrire.",
        "Lore2_en": "Elle a usé de magie lors de l’enlèvement.",
        "Lore3_en": "Elle chausse du moyen.",
        "Lore4_en": "Elle est chrétienne.",
        "Lore5_en": "Elle connaît le domaine, ou dispose de plans.",
        "Lore6_en": "Elle n’est pas en deuil.",
        "Lore7_en": "Elle ne fait pas partie du personnel.",
        "Lore8_en": "C’est un artiste accompli.",
        "Lore9_en": "Elle n’avait aucun passé avec Mlle Deane avant le manoir.",
    },
    "Blank": {"Lore9_en": "La petite cinquantaine."},

    # ------------------------------------------------- unmet-guest placeholders
    "D'ArcyUnknown": {"AltName": "Femme en moutarde"},
    "DupréUnknown": {"AltName": "Homme en violet"},
    "SkerritUnknown": {"AltName": "Homme au monocle "},
    "ArwaUnknown": {"AltName": "Grande femme"},
    "CaitlinUnknown": {"AltName": "Gouvernante"},
    "IvyUnknown": {"AltName": "Femme en robe bleue"},
    "LanFenUnknown": {"AltName": "Femme en noir"},
    "DarraghUnknown": {"AltName": "Maître d’écurie"},
    "CorentineUnknown": {"AltName": "Femme en violet"},
    "DoyleUnknown": {"AltName": "Portier"},
    "VarleyUnknown": {"AltName": "Gérant"},
    "InesUnknown": {"AltName": "Femme au châle bleu"},
    "CathalUnknown": {"AltName": "Homme à la canne"},
    "EttieneUnknown": {"AltName": "Homme à lunettes"},
    "FiadhUnknown": {"AltName": "Femme rousse"},
    "CarmellaUnknown": {"AltName": "Femme en bleu"},
    "SinnottUnknown": {"AltName": "Prêtre"},
    "HazelUnknown": {"AltName": "Femme en rouge"},
    "RevUnknown": {"AltName": "Révérend"},
    "HigginsUnknown": {"AltName": "Invité"},
    "JBlakeUnknown": {"AltName": "Le marquis "},
    "OFinnUnknown": {"AltName": "Homme barbu"},
    "RuairiUnknown": {"AltName": "Homme en costume brun"},
    "CoventryUnknown": {"AltName": "Homme en gris"},
    "SaoirseUnknown": {"AltName": "Cuisinière"},
    "1TempUnknown": {"AltName": "Invité"},

    # ---------------------------------------------------------- dream figures
    "The Haunted Man (Blake)": {"AltName": "L’Homme hanté "},
    "The Abstracted (Coventry)": {"AltName": "L’Absent"},
    "The Sunken (O Finn)": {"AltName": "Le Noyé"},
    "The Stag (carmella)": {"AltName": "La Déesse-Cerf"},
    "The Owl (Skerritt)": {"AltName": "Le Vieux Hibou sage"},
    "The Moon (ivy)": {"AltName": "Dame Lune"},
    "The Sun (Lan Fen)": {"AltName": "Dame Soleil"},
    "The Wolf (Corentine)": {"AltName": "Le Loup"},
    "The Angel (Cathal)": {"AltName": "Un ange"},
    "The Corpse (Etienne)": {"AltName": "Le Cadavre"},
    "The Bird (Ines)": {"AltName": "L’Oiseau"},
    "The Wretched (Hazel)": {"AltName": "La Misérable"},
    "The Crow (Ruairí)": {"AltName": "Le Corbeau"},
    "Death (dupre)": {"AltName": "La Mort"},
    "Goibhniu": {"AltName": "L’Homme cornu"},
    "The Cat (Darcy)": {"AltName": "Le Chat"},
    "The Void (Sinnott)": {"AltName": "Le Vide"},
    "The Fracture (Arwa)": {"AltName": "La Fêlure"},

    # ------------------------------------------------------ voices and places
    "Familiar Voice": {"AltName": "Une voix familière"},
    "Unknown Thing": {"AltName": "Le Gardien"},
    "Unknown Female Voice": {"AltName": "Voix de femme"},
    "Unknown Male Voice": {"AltName": "Voix d’homme"},
    "Second Unknown Male Voice": {"AltName": "Voix d’un second homme inconnu"},
    "Congregation": {"AltName": "Voix d’une femme inconnue"},
    "Spirit": {"AltName": "Esprit"},
    "staffFinale_V&D": {"AltName": "MM. Varley et Hunter"},
    "staffFinale_V&D&D": {"AltName": "MM. Varley, Hunter et Doyle"},
    "staffFinale_V&D&D&S": {"AltName": "MM. Varley, Hunter et Doyle, et Mlle Murphy"},
    "staffFinale_V&D&D&S&C": {"AltName": "MM. Varley, Hunter et Doyle, Mlle Murphy et Mme Joyce"},

    "Blake Manor": {
        "AltName": "Blake Manor", "FullName": "Blake Manor", "Title_en": "L’hôtel",
        "castBio": "Un ancien manoir devenu hôtel, à l’extrême ouest de l’Irlande. Il fut bâti au milieu du XVIIe siècle par Edward Blake.",
        "hasNotTalkedWithBio": "Un ancien manoir devenu hôtel, à l’extrême ouest de l’Irlande. Il fut bâti au milieu du XVIIe siècle par Edward Blake.",
    },
    "West Annex": {"AltName": "Aile ouest", "FullName": "Aile ouest", "Title_en": "L’hôtel"},
    "East Annex": {"AltName": "Aile est", "FullName": "Aile est", "Title_en": "L’hôtel"},
    "Stables": {"AltName": "Écuries", "FullName": "Écuries", "Title_en": "L’hôtel"},
    "Front Door": {"AltName": "Porte d’entrée", "FullName": "Porte d’entrée", "Title_en": "L’hôtel"},
    "Gardens": {"AltName": "Jardins", "FullName": "Jardins", "Title_en": "L’hôtel"},
    "South East Basement": {"AltName": "Sous-sol sud-est", "FullName": "Sous-sol sud-est", "Title_en": "L’hôtel"},
    "South West Basement": {"AltName": "Sous-sol sud-ouest", "FullName": "Sous-sol sud-ouest", "Title_en": "L’hôtel"},
    "Eastern Basement": {"AltName": "Sous-sol est", "FullName": "Sous-sol est", "Title_en": "L’hôtel"},
    "Northern Basement": {"AltName": "Sous-sol nord", "FullName": "Sous-sol nord", "Title_en": "L’hôtel"},
    "Room 2": {"AltName": "Chambre 2", "FullName": "Chambre 2", "Title_en": "L’hôtel"},
    "Room 7": {"AltName": "Chambre 7", "FullName": "Chambre 7", "Title_en": "L’hôtel"},
    "Room 15": {"AltName": "Chambre 15", "FullName": "Chambre 15", "Title_en": "L’hôtel"},
    "Room 21": {"AltName": "Chambre 21", "FullName": "Chambre 21", "Title_en": "L’hôtel"},
}


# The 44 "unknown guest" and dream-figure actors carry 15 placeholder lore slots
# each, all literally "...". They show as blanks on the cast card until you have met
# the person. Generated rather than listed: 660 identical entries.
_PLACEHOLDER_ACTORS = [
    name for name, fields in ACTORS.items()
    if name.endswith("Unknown") or name in {
        "The Haunted Man (Blake)", "The Abstracted (Coventry)", "The Sunken (O Finn)",
        "The Stag (carmella)", "The Owl (Skerritt)", "The Moon (ivy)", "The Sun (Lan Fen)",
        "The Wolf (Corentine)", "The Angel (Cathal)", "The Corpse (Etienne)",
        "The Bird (Ines)", "The Wretched (Hazel)", "The Crow (Ruairí)", "Death (dupre)",
        "Goibhniu", "The Cat (Darcy)", "The Void (Sinnott)", "The Fracture (Arwa)",
    }
]
for _name in _PLACEHOLDER_ACTORS:
    for _i in range(1, 16):
        ACTORS[_name][f"Lore{_i}_en"] = "…"
